// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class HHDragDropItem:UIDragDropItem
{
	public Transform sourceContainer;
	public Transform targetContainer;

	public HHObjectItem object1;
	public HHObjectItem object2;

	protected override void OnDragDropStart ()
	{
		sourceContainer = this.transform.parent;
		object1 = this.GetComponent<HHObjectItem>();

		base.OnDragDropStart();
	}

	protected override void OnDragDropRelease (GameObject surface)
	{
		if (surface.name != "HHObjectItem") 
		{
			object1.ResetCenter();
			return;
		}
		targetContainer = surface.transform.parent;


		HHObjectItemContainer c1 = sourceContainer.GetComponent<HHObjectItemContainer>();
		HHObjectItemContainer c2 = targetContainer.GetComponent<HHObjectItemContainer>();

		object2 = c2.Child;
		if (!c1.IsNearBy(c2)) 
		{
			object1.ResetCenter();
			return;
		}
		object1.Container = c2;
		object2.Container = c1;


		c1.ScanHorizontalDirection();
		c1.ScanVerticalDirection();
		c2.ScanHorizontalDirection();
		c2.ScanVerticalDirection();

		HHEstimateDismissManager.Refresh((bool result)=>{
			if (result) 
			{
				object1.Container = c1;
				object2.Container = c2;
			}
		});

		base.OnDragDropRelease (surface);
	}
}


