// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class HHGameLayoutPanel
{
	private HHGameLayoutPanel ()
	{
	}

	/**
	 * 
	 * 
	 * 
	 * 
	 */
	private const float GamePanelSize = 125f;

	private static List<HHGameCell> cell_list = new List<HHGameCell>();

	public static UIPanel GetGamePanel(int size,GameObject parent)
	{
		UIPanel panel = NGUITools.AddChild<UIPanel>(parent);

		panel.SetRect(0f,0f,GamePanelSize,GamePanelSize);
		panel.transform.localPosition = new Vector3(0f,0f,0f);

		//
		float cell_size = GamePanelSize / size;

		//
		HHGameCell.CellList = HHGameLayoutPanel.cell_list;

		//
		HHGameCell.CellSize = size;

		//
		float min_x = 0 - cell_size / 2;
		float max_y = ( GamePanelSize - cell_size ) / 2 ;

		//create list cell
		for (int i = 0; i < size; i++) 
		{
			for (int j = 0; j < size; j++) 
			{
				HHGameCell item = NGUITools.AddChild<HHGameCell>(panel.gameObject);

				item.Index = i * size + j;

				float x = min_x + j % size * cell_size;
				float y = max_y - i * cell_size;

				item.SetCellRect(new Vector4(x,y,cell_size,cell_size));

				HHGameCell.CellList.Add(item);
			}
		}

		return panel;
	}
}


